### ISSUE TITLE
Repair runtime crashes

### ISSUE THREAD

**Issue by novotnj3** [novotnj3/MUSCIMarker#7]
The applications runs on Android! Test all the features and repair errors. Currently we are aware of these errors:

- [x]  Setting (no configuration file)

- [x]  App crashes on exit (without any explicit reason)

**Comment by hajicj** [comment]
Potential filesystem-related reasons I can think of for a crash on exit:

* Attempting to close off the tracking log
* Recording last open files into the config
* Attempting a recovery dump (if configured to do so)
* Cleaning the temp dir

**Comment by novotnj3** [comment]
Solved. :)
